truths = [
    'When was the last time you peed in bed?',
    'What is the biggest lie you have ever told?',
    'Tell us your most embarrassing vomit story.',
    'Have you ever made out with someone here?',
    'Have you ever cheated or been cheated on?',
    'What are your top three turn-ons?',
    'What is your deepest darkest fear?',
    'What is the most childish thing you still do?',
    'What is something your friends would never expect that you do?',
    'Who is the person you most regret kissing?',
    'When was the last time you lied?',
    'Who was the last person you licked?',
    'What is the most embarrassing picture of you?',
    'What’s the most embarrassing thing you’ve ever done?',
    'Have you ever broken the law?',
    'Do you have any fetishes?',
    'What’s the worst thing you’ve ever done?',
    'What’s the worst thing you’ve ever said to anyone?',
    'What’s the biggest misconception about you?',
    'What’s a secret you’ve never told anyone?',
    'What would you do if you were the opposite sex for a week?',
    'What’s the worst time you let someone take the blame for something you did?',
    'What do most people think is true about you, but isn’t?',
    'What’s your biggest regret?',
    'What are your thoughts on polyamory?',
    'What is the biggest thing you’ve gotten away with?',
    'Why did you break up with your last boyfriend or girlfriend?',
    'What is the most embarrassing series of texts you have on your phone?',
    'When was the last time you cried?',
    'What’s your biggest fantasy?',
    'Tell me about your first kiss',
    'What is the most embarrassing thing in your room?',
    'What was the most awkward romantic encounter you have had?',
    'Do you have a hidden talent?',
    'What is the stupidest thing you have ever done?',
    'What pictures or videos of you do you wish didn’t exist?',
    'What is your biggest regret?',
    'Who is your crush?',
    ' Tell me about your most awkward date.',
    'What is the naughtiest thing you’ve done in public?',
    'What is the most expensive thing you have stolen?',
    'What’s something you’re glad your mum doesn’t know about you?',
    'What is something that people think you would never be into, but you are?',
    'Who was your first celebrity crush?',
    'What’s the worst intimate experience you’ve ever had?',
    'Have you ever cheated in an exam?',
    'What’s the drunkest you’ve ever been?',
    'What is the silliest thing you have an emotional attachment to?',
    'What’s the biggest mistake you’ve ever made?',
    'What’s the most disgusting thing you’ve ever done?',
    'Who would you like to kiss in this room?',
    'Where’s the weirdest place you’ve had sex?',
    'What’s the worst thing anyone’s ever done to you?',
    'What’s your worst habit?',
    'What’s the strangest dream you’ve had?',
    'Have you ever been caught doing something you shouldn’t have?',
    'What’s the worst date you’ve been on?',
    'Have you ever lied to get out of a bad date?',
    'Have you ever peed in the shower?',
    'Have you ever shit yourself since you were a child?',
    'What is the most embarrassing thing your parents have caught you doing?',
    'What’s the most trouble you’ve been in?',
    'Who is the sexiest person here?',
    'What secret about yourself did you tell someone in confidence and then they told a lot of other people?',
    'When was the most inappropriate time you farted?',
    'What is the scariest dream you have ever had?',
    'What is the grossest thing that has come out of your body?',
    'What is your favourite thing that your boyfriend or girlfriend does?',
    'Who have you loved but they didn’t love you back?',
    ' If you starred in a romance, what would it be like?',
    'What was the cruellest joke you played on someone?',
    'What is the most embarrassing thing you have put up on social media?',
    'What is the grossest thing you have had in your mouth?',
    'Tell me about the last time someone unexpectedly walked in on you while you were naked.',
    'What is the most embarrassing nickname you have ever had?',
    'Describe your most recent romantic encounter in detail.',
    'What is the weirdest thing you have done for a boyfriend or girlfriend?',
    'Is it true that you (whatever you or the group suspects they do / did)?',
    'When was the last time you wiped a booger off on something that shouldn’t have boogers on it?',
    'What do you really hope your parents never find out about?',
    'Tell me something you don’t want me to know.',
    'What have you done that people here would judge you most for doing?',
    'What is something that you have never told anyone?',
    'What is the most disgusting habit you have?'
]
daers = [
    'Do 100 squats.',
    'Show the most embarrassing photo on your phone.',
    'Give a foot massage to the person on your right.',
    'Say something dirty to the person on your left.',
    'Let the rest of the group DM someone from your Instagram account.',
    'Eat a banana without using your hands.',
    'Twerk for a minute.',
    'Keep your eyes closed until it’s your go again.',
    'Like the first 15 posts on your Facebook newsfeed.',
    'Send a sext to the last person in your phonebook.',
    'Eat a raw onion.',
    'Keep three ice cubes in your mouth until they melt.',
    'Give a lap dance to someone of your choice.',
    'Yell out the first word that comes to your mind.',
    'Show off your orgasm face.',
    'Empty out your wallet/purse and show everyone what’s inside.',
    'Show the last five people you texted and what the messages said.',
    'Try to put your whole fist in your mouth.',
    'Remove four items of clothing.',
    'Eat a spoonful of mustard.',
    'Put 10 different available liquids into a cup and drink it.',
    'Do your best impression of a baby being born.',
    'Try to lick your elbow.',
    'Pretend to be the person to your right for 10 minutes.',
    'Be someone’s pet for the next 5 minutes.',
    'Try to drink a glass water while standing on your hands.',
    'Do your best sexy crawl.',
    'Say two honest things about everyone else in the group.',
    'Put as many snacks into your mouth at once as you can.',
    'Try and make the group laugh as quickly as possible.',
    'Let someone shave part of your body.',
    'Tell everyone an embarrassing story about yourself.',
    'Post the oldest selfie on your phone on Instagram Stories.',
    'For a guy, put on makeup. For a girl, wash off your make up.',
    'Do four cartwheels in row.',
    'Tell the saddest story you know.',
    'Belly dance like your life depended on it.',
    'Curse like sailor for 20 seconds straight.',
    'Howl like a wolf.',
    'Dance without music for one minute.',
    'Pole dance with an imaginary pole.',
    'Let someone else tickle you and try not to laugh.',
    'Serenade the person to your right.',
    'Talk in an accent for the next 3 rounds.',
    'Make every person in the group smile, keep going until everyone has cracked a smiled.',
    'Kiss the person to your left.',
    'Attempt to do a magic trick.',
    'Eat five tablespoons of a condiment.',
    'Attempt to breakdance for one minute.',
    'Let the group give you a new hairstyle.',
    'Do the worm.',
    'Take a shower with your clothes on.',
    'Break two eggs on your head.',
    'Sell a piece of trash to someone in the group using your best salesmanship.',
    'Attempt to walk on your hands for as far as you can.',
    'Imitate a celebrity every time you talk.',
    'Try to juggle 2 or 3 items of the group’s choosing.',
    'Gargle something that shouldn’t be gargled, but won’t hurt you.',
    'Get slapped on the face by the person of your choosing.',
    'Spin an imaginary hula hoop around your waist for the rest of the round.',
    'Seduce a member of the same gender in the group.',
    'Compose a poem on the spot based on something the group comes up with.',
    'Poll dance for 1 minute with an imaginary pole.',
    'Choose someone from the group to give you a spanking.',
    'Post an extremely unflattering picture of yourself to the social media outlet of your choosing.',
    'Hold a funny face for the rest of the round.',
    'Imagine something in your room. Now spell it with your nose and keep spelling it with your nose until someone from the group guesses what you are trying to spell.',
    'After the group chooses one rude word, sing a song and insert that rude word once into every line of the song.',
    'Drag your butt on the carpet like a dog from one end of the room to the other.',
    'Open a bag of snacks or candy using only your mouth, no hands or feet.',
    'Bend at the waist so that you are looking behind you between your legs. Now run backwards until you can tag someone with your butt.',
    'Go to the bathroom, take off your underwear and put it on your head. Wear it on your head for the rest of the game.',
    'Act like whatever animal someone yells out for the next 1 minute.',
    'Eat one teaspoon of the spiciest thing you have in the kitchen.',
    'Transfer an ice cube from your mouth to the person’s mouth on your right.',
    'Call the 3rd contact in your phone and sing them 30 seconds of a song that the group chooses.No talking.',
    'Pretend to be a food. Don’t pretend to eat the food, pretend to be the food. Keep pretending until someone in the group guesses the food you are.',
    'Drop something in the toilet and then reach in to get it.',
    'Find the person whose first name has the same letter as your first name or whoever’s first name’s first letter is closest to yours. Now lick their face.',
    'Sit in a spinning chair and have the group spin you for 30 seconds.', ','
    'Jump up and down as high as you can go for a full minute.',
    'Let two people give you a wet willy at the same time.',
    'Sing a praise song about a person of the groups choosing.',
    'Depict a human life through interpretive dance.',
    'Dance with no music for 1 minute.',
    'Write something embarrassing somewhere on your body (that can be hidden with clothing) with a permanent marker.',
    'Beg and plead the person to your right not to leave you for that other boy or girl.',
    'Put ice cubes down your pants.',
    'Stick your arm into the trash can past your elbow.',
    'Lick the floor.',
    'Switch clothes with someone of the opposite sex in the group for three rounds.',
    'Let the group pose you in an embarrassing position and take a picture.',
    'Give someone your phone and let them send one text to anyone in your contacts.',
    'Let the group look through your phone for one minute.',
    'Drink a small cup of a concoction that the group makes.',
    'Let the person to your left draw on your face with a pen.',
    'Imitate popular YouTube videos until someone can guess the video you are imitating.',
    'Grab a trash can and make a hoop with your hands above the trash can. Have other members of the group try to shoot trash through your hoop.',
    'Make up a 30-second opera about a person or people in the group and perform it.',
    'Do pushups until you can’t do any more, wait 5 seconds, and then do one more.',
]
